format = """
[](fg:#ffffff)\
$os\
[](fg:#ffffff bg:c2)\
$directory\
[](fg:c2 bg:#303030)\
$git_branch\
$git_status\
$git_metrics\
$fill\
$nodejs\
$php\
$go\
$dotnet\
$python\
$java\
$c\
$kubernetes\
$cmd_duration\
$shell\
[](fg:c4 bg:c2)\
$time\
[](fg:c2 bg:c1)\
$username\
[](fg:#004480)\
$line_break\
$character\
"""

palette = 'main'
add_newline = true

[palettes.main]
c1 = '#004480' # blue light
c2 = '#002240' # blue dark
c3 = '#c6e7ff' # blue extra light
c4 = '#303030' # gray
c5 = '#808080' # gray light

[os]
format = '[$symbol ](fg:#000000 bg:#ffffff)'
disabled = false

[os.symbols]
Alpine = ''
Amazon = ''
Android = ''
Arch = ''
CentOS = ''
Debian = ''
EndeavourOS = ''
Fedora = ''
FreeBSD = ''
Garuda = ''
Gentoo = ''
Linux = ''
Macos = ''
Manjaro = ''
Mariner = ''
Mint = ''
NetBSD = ''
NixOS = ''
OpenBSD = '' # ''
OpenCloudOS = '☁️'
openEuler = ''
openSUSE = ''
OracleLinux = '⊂⊃'
Pop = '' # ''
Raspbian = ''
Redhat = ''
RedHatEnterprise = ''
Solus = '' # ' '
SUSE = ''
Ubuntu = ''
Unknown = ''
Windows = ''

[directory]
format = '[ 󰷏 $path ](fg:c3 bg:c2 italic)'
truncation_length = 3
fish_style_pwd_dir_length = 1

[directory.substitutions]
'Development' = 'dev'

[git_branch]
format = '[ 󰘬 $branch ](fg:#808080 bg:c4)'

[git_metrics]
format = '([+$added ]($added_style))([-$deleted ]($deleted_style))'
added_style = 'fg:#808080 bg:c4'
deleted_style = 'fg:#808080 bg:c4'
disabled = false

[git_status]
format = '([$all_status$ahead_behind ](fg:#808080 bg:c4))'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'
ahead = '⇡${count}'

[direnv]
disabled = false

[nodejs]
format = '[ $symbol$version ](fg:#ffffff bg:c4)'

[php]
format = '[ $symbol$version ](fg:#ffffff bg:c4)'

[kubernetes]
format = '([ $symbol($version )](fg:#ffffff bg:c4))'
disabled = false

[helm]
format = '([ $symbol($version )](fg:#ffffff bg:c4))'

[golang]
format = '[ $symbol$version ](fg:#ffffff bg:c4)'

[dotnet]
format = '[ $symbol$tfm ](fg:#ffffff bg:c4)'
fkubernetesrmat = '[ $symbol$tfm ](fg:#ffffff bg:c4)'
helmrmat = '[ $symbol$tfm ](fg:#ffffff bg:c4)'
symbol = ' .NET '

[python]
format = '[ $symbol$version ](fg:#ffffff bg:c4)'
symbol = ' '

[java]
format = '[ $symbol$version ](fg:#ffffff bg:c4)'
symbol = ' '

[c]
format = '[ $symbol$version ](fg:#ffffff bg:c4)'
symbol = ' '

[fill]
style = 'fg:c5 bg:c4'
symbol = '.'

[cmd_duration]
min_time = 500
format = '[ $duration ](fg:yellow bg:c4 bold)'

[shell]
format = '[  $indicator ](c5 bg:c4)'
unknown_indicator = 'shell'
powershell_indicator = 'powershell'
fish_indicator = 'fish'
disabled = false

[time]
disabled = false
format = '[ $time ](fg:c3 bg:c2)'
time_format = '󰦖 %H:%M'

[username]
format = '[  $user ](fg:#ffffff bg:c1)'
show_always = true

[character]
format = """
[╰─$symbol](fg:c4) """
success_symbol = '[≫](fg:bold white)'
error_symbol = '[×](fg:bold red)'