name: 'Setup Nix Build Environment'
description: 'Sets up Nix with flakes, Cachix, and frees up disk space for building'
inputs:
  cachix-auth-token:
    description: 'Cachix authentication token'
    required: false
    default: ''
runs:
  using: 'composite'
  steps: 
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main

    - name: Install Nix
      uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          experimental-features = nix-command flakes
          access-tokens = github.com=${{ github.token }}

    - name: Setup Cachix
      uses: cachix/cachix-action@v16
      with:
        name: nix-community
        authToken: ${{ inputs.cachix-auth-token }}