name: 'Setup Nix Build Environment'
description: 'Sets up Nix with flakes, Cachix, and frees up disk space for building'
inputs:
  cachix-auth-token:
    description: 'Cachix authentication token'
    required: false
    default: ''
runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install Nix
      uses: cachix/install-nix-action@v27
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          experimental-features = nix-command flakes
          access-tokens = github.com=${{ github.token }}

    - name: Setup Cachix
      uses: cachix/cachix-action@v15
      with:
        name: nix-community
        authToken: ${{ inputs.cachix-auth-token }}

    - name: Free up disk space
      shell: bash
      run: |
        # Remove unnecessary packages to free up space
        sudo apt-get purge -y \
          '^dotnet-.*' \
          '^llvm-.*' \
          'php.*' \
          '^mongodb-.*' \
          '^mysql-.*' \
          azure-cli \
          google-cloud-* \
          hhvm \
          google-chrome-stable \
          firefox \
          powershell \
          mono-devel \
          libgl1-mesa-dri
        sudo apt-get autoremove -y
        sudo apt-get clean
        
        # Remove large directories
        sudo rm -rf \
          /usr/share/dotnet \
          /usr/local/lib/android \
          /opt/ghc \
          /opt/hostedtoolcache/CodeQL \
          /usr/local/share/boost \
          /usr/lib/jvm
        
        df -h