name: Build ISO Images

on:
  workflow_dispatch:
    inputs:
      build_target:
        description: 'Which ISO to build'
        required: true
        default: 'both'
        type: choice
        options:
          - 'both'
          - 'steam-handheld'
          - 'common'

jobs:
  build-steam-handheld:
    if: ${{ github.event.inputs.build_target == 'both' || github.event.inputs.build_target == 'steam-handheld' }}
    uses: ./.github/workflows/build-single-iso.yml
    with:
      iso-type: steam-handheld
    secrets:
      CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}

  build-common:
    if: ${{ github.event.inputs.build_target == 'both' || github.event.inputs.build_target == 'common' }}
    uses: ./.github/workflows/build-single-iso.yml
    with:
      iso-type: common
    secrets:
      CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}

  summary:
    needs: [build-steam-handheld, build-common]
    runs-on: ubuntu-latest
    if: always()
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Download all release notes
        uses: actions/download-artifact@v5
        with:
          pattern: "*-release-notes"
          merge-multiple: true

      - name: Combine release notes
        run: |
          echo "# ISO Build Summary" > combined_notes.md
          echo "" >> combined_notes.md
          echo "**Workflow**: ${{ github.workflow }}" >> combined_notes.md
          echo "**Trigger**: Manual dispatch" >> combined_notes.md
          echo "**Repository**: ${{ github.repository }}" >> combined_notes.md
          echo "**Commit**: ${{ github.sha }}" >> combined_notes.md
          echo "**Build Date**: $(date -u '+%Y-%m-%d %H:%M:%S UTC')" >> combined_notes.md
          echo "" >> combined_notes.md
          
          if ls release_notes.md 2>/dev/null; then
            cat release_notes.md >> combined_notes.md
          fi

      - name: Upload combined summary
        uses: actions/upload-artifact@v4
        with:
          name: build-summary
          path: combined_notes.md

      - name: Build Status Summary
        run: |
          echo "## Build Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          if [ "${{ needs.build-steam-handheld.result }}" == "success" ] || [ "${{ needs.build-common.result }}" == "success" ]; then
            echo "✅ At least one ISO build completed successfully" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ All ISO builds failed or were cancelled" >> $GITHUB_STEP_SUMMARY
          fi
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Build Status:" >> $GITHUB_STEP_SUMMARY
          echo "- Steam Handheld ISO: ${{ needs.build-steam-handheld.result || 'skipped' }}" >> $GITHUB_STEP_SUMMARY
          echo "- Common ISO: ${{ needs.build-common.result || 'skipped' }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Check the artifacts section for downloadable ISO files." >> $GITHUB_STEP_SUMMARY